name: Read text file

on:
 workflow_dispatch:
  inputs:
    select-file:
      description: 'Select a text file to read'
      type: choice
      required: true
      default: 'tajvir.txt'
      options:
      - tajvir.txt
      - staging
      - production

env:
  Tajvir: "This is variable"

jobs: 
  read-file:
   runs-on: ubuntu-latest

   env:
    Tajvir_ENV: ${{ secrets.Tajvir_ENV }}

   steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print TAJVIR_ENV secret variable
        run: |
          echo "The environment variable of TAJVIR_ENV is: $Tajvir_ENV"

      - name: Print env variable name
        run: |
          echo "Env Variable: $Tajvir" 

      - name: Print user input
        run: |
          echo "User Input: ${{ github.event.inputs.select-file }}"  

      - name: read text file
        run:
          cat tajvir.txt 

      - name: Check the user input
        run: |
          if [ "${{ github.event.inputs.select-file }}" == "tajvir.txt" ]; then
            echo "You selected tajvir.txt"
          elif [ "${{ github.event.inputs.select-file }}" == "staging" ]; then
            echo "You selected staging"
          elif [ "${{ github.event.inputs.select-file }}" == "production" ]; then
            echo "You selected production"
          else
            echo "Invalid selection"
          fi
   
  