name: Read text file

on:
 workflow_dispatch:
  inputs:
    select-file:
      description: 'Select a text file to read'
      type: choice
      required: true
      default: 'tajvir.txt'

      options:
      - tajvir.txt
      - staging
      - production

jobs: 
  read-file:
   runs-on: ubuntu-latest

   steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print user input
        run: |
          echo "User Input: ${{ github.event.inputs.select-file }}"  

      - name: read text file
        run:
          cat tajvir.txt 
   
  